### ISSUE TITLE
filestat2 함수 구현하기

### ISSUE THREAD

**Issue by tentasys** [tentasys/Project2#2]
파일 정보를 받아오는 filestat2 함수를 구현합니다.

**Comment by CreatiCoding** [comment]
#9 작업 완료

**Comment by CreatiCoding** [comment]
stat 구현시 참고 자료 입니다.
![image](https://user-images.githubusercontent.com/33514304/39289606-cd200504-4967-11e8-8b96-674bb0a32f50.png)
자료 출처 : https://linux.die.net/man/2/stat
