### ISSUE TITLE
프로젝트 intergrate/compile

### ISSUE THREAD

**Issue by tentasys** [tentasys/Project2#21]
부분 모듈을 합치고 컴파일하는 작업을 진행합니다.

**Comment by tentasys** [comment]
@kyungjin1121 
![image](https://user-images.githubusercontent.com/13197487/39853175-949ecac2-545b-11e8-838b-9680d17028fb.png)
세미콜론이 없지만 일정상 제가 넣고 진행하께용

**Comment by tentasys** [comment]
![image](https://user-images.githubusercontent.com/13197487/39854452-bb055ee0-5462-11e8-8a39-8b97e697ca62.png)
프로그램이 뭔가 이상하네요...ㅠ 혹시 테스트 부탁드릴수 있나요
test_master branch로 checkout하고 테스트 진행해주시면 감사하겠습니다ㅠㅠ
컴파일 방법은 gcc -o main main.c 이지만 다들 알고계실거라 생각합니당
해당 branch에 text1 text2 모두 만들어 놓았어요
@kyungjin1121  @CreatiCoding  @dkflfd

**Comment by tentasys** [comment]
아마도...git pull origin test_master 하면 테스트용으로 만든 브랜치 가져올 수 있을겁니다..

**Comment by tentasys** [comment]
아마도...git pull origin test_master 하면 테스트용으로 만든 브랜치 가져올 수 있을겁니다..

**Comment by CreatiCoding** [comment]
![image](https://user-images.githubusercontent.com/33514304/39855670-c2c6d712-5467-11e8-81ca-2c2055fe71d1.png)
@tentasys 
테스트 결과입니다.
