### ISSUE TITLE
blockcmp 함수 구현하기

### ISSUE THREAD

**Issue by tentasys** [tentasys/Project2#7]
두 개의 파일 블락 수를 비교하는 함수 구현하기

**Comment by kyungjin1121** [comment]
contents about st_blocks 
<img width="691" alt="2018-05-03 1 31 19" src="https://user-images.githubusercontent.com/25261258/39560291-d353e650-4ed7-11e8-85d8-a8687f17e609.png">
reference url : http://man7.org/linux/man-pages/man2/stat.2.html
